---
plugins:
  - jest
  - security
env:
  node: true
  jest: true
  browser: true
extends:
  - 'airbnb-typescript'
  - 'airbnb/hooks'
  - 'plugin:jest/recommended'
  - 'plugin:security/recommended'
rules:
  no-console:
    - 2
    - allow:
        - warn
        - error
  max-len:
    - 2
    - 120
    - ignoreUrls: true
      ignoreComments: true
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  class-methods-use-this:
    - 0
  object-curly-newline: 0
  react/prop-types: 0
