---
parserOptions:
  project: './tsconfig.json'
plugins:
  - jest
  - security
  - '@typescript-eslint'
env:
  node: true
  jest: true
  browser: true
extends:
  - 'airbnb-typescript'
  - 'airbnb/hooks'
  - 'plugin:jest/recommended'
  - 'plugin:security/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
rules:
  no-console:
    - 2
    - allow:
        - warn
        - error
  max-len:
    - 2
    - 120
    - ignoreUrls: true
      ignoreComments: true
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  class-methods-use-this:
    - 0
  object-curly-newline: 0
  '@typescript-eslint/indent': 0
  indent:
    - 2
    - 2
    - SwitchCase: 1
      VariableDeclarator: 1
      outerIIFEBody: 1
      FunctionDeclaration:
          parameters: 1
          body: 1
      FunctionExpression:
          parameters: 1
          body: 1
      CallExpression:
          arguments: 1
      ArrayExpression: 1
      ObjectExpression: 1
      ImportDeclaration: 1
      flatTernaryExpressions: false
      ignoreComments: false
  react/prop-types: 0
  react/require-default-props: 0
  no-shadow: [2, {allow: ['error', 'callback', 'context', 'ctx']}]
