env:
  global:
    # repository id on Code Climate, individual for every repository
    - CC_TEST_REPORTER_ID=e96c1f1ec9fec8d2710c9983c93c1b418e0d18b7147cc9f8363579e70839015f
services:
  - docker
language: node_js
node_js:
  - node

before_install:
  - docker-compose up --build -d

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - docker-compose exec -T design-server yarn run lint
  # - docker-compose exec -T design-server yarn run typecheck
  # - docker-compose exec -T design-server yarn run spellcheck
  - docker-compose exec -T design-server yarn run migrate
  - docker-compose exec -T design-server yarn test

after_script:
  - docker-compose logs design-server > logs/server.log || true
  - docker-compose down -v
  - ./cc-test-reporter after-build --debug -t lcov --exit-code $TRAVIS_TEST_RESULT
