version: '3'

services:
  db:
    image: postgres:11.6-alpine
    container_name: db
    ports:
      - 5432
    tmpfs:
      - /var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ./.env.ci:/srv/app/.env:ro
    depends_on:
      - db
    command: ["npm", "run", "server"]
